# Add Rack Domain Failure Before Applying The Object Store

apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: anbar-rc3-rack
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: rack
    replicated:
      size: 2 
  dataPool:
    failureDomain: rack
    replicated:
      size: 2
  preservePoolsOnDelete: true
  gateway:
    sslCertificateRef:
    port: 80
    # securePort: 443
    instances: 1