apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    allowUnsupported: false
    image: quay.io/ceph/ceph:v17.2.7
  cleanupPolicy:
    allowUninstallWithVolumes: false
    confirmation: ''
    sanitizeDisks:
      dataSource: zero
      iteration: 1
      method: quick
  continueUpgradeAfterChecksEvenIfNotHealthy: false
  crashCollector:
    disable: false
  dashboard:
    enabled: true
    ssl: false
  dataDirHostPath: /var/lib/rook
  disruptionManagement:
    managePodBudgets: true
    osdMaintenanceTimeout: 30
    pgHealthCheckTimeout: 0
  external: {}
  healthCheck:
    daemonHealth:
      mon:
        disabled: false
        interval: 45s
      osd:
        disabled: false
        interval: 60s
      status:
        disabled: false
        interval: 60s
    livenessProbe:
      mgr:
        disabled: false
      mon:
        disabled: false
      osd:
        disabled: false
    startupProbe:
      mgr:
        disabled: false
      mon:
        disabled: false
      osd:
        disabled: false
  logCollector:
    enabled: true
    maxLogSize: 500M
    periodicity: daily
  mgr:
    allowMultiplePerNode: false
    count: 2
    modules:
      - enabled: true
        name: pg_autoscaler
  mon:
    allowMultiplePerNode: false
    count: 3
  monitoring:
    enabled: false
    metricsDisabled: false
  network:
    connections:
      compression:
        enabled: false
      encryption:
        enabled: false
      requireMsgr2: false
    multiClusterService: {}
    provider: host
  priorityClassNames:
    mgr: system-cluster-critical
    mon: system-node-critical
    osd: system-node-critical
  removeOSDsIfOutAndSafeToRemove: false
  security:
    keyRotation:
      enabled: false
    kms: {}
  skipUpgradeChecks: false
  storage:
    flappingRestartIntervalHours: 0
    nodes:
      - devices:
          - config:
              osdsPerDevice: '1'
            name: /dev/sdb
          - config:
              osdsPerDevice: '1'
            name: /dev/sdc
          - config:
              osdsPerDevice: '1'
            name: /dev/sdd
          - config:
              osdsPerDevice: '1'
            name: /dev/sde
        name: cephak01
      - devices:
          - config:
              osdsPerDevice: '1'
            name: /dev/sdb
          - config:
              osdsPerDevice: '1'
            name: /dev/sdc
          - config:
              osdsPerDevice: '1'
            name: /dev/sdd
          - config:
              osdsPerDevice: '1'
            name: /dev/sde
        name: cephak02
      - devices:
          - config:
              osdsPerDevice: '1'
            name: /dev/sdb
          - config:
              osdsPerDevice: '1'
            name: /dev/sdc
          - config:
              osdsPerDevice: '1'
            name: /dev/sdd
          - config:
              osdsPerDevice: '1'
            name: /dev/sde
        name: cephak03
      - devices:
          - config:
              osdsPerDevice: '1'
            name: /dev/sdb
          - config:
              osdsPerDevice: '1'
            name: /dev/sdc
          - config:
              osdsPerDevice: '1'
            name: /dev/sdd
          - config:
              osdsPerDevice: '1'
            name: /dev/sde
        name: cephak04
    onlyApplyOSDPlacement: false
    store: {}
    useAllDevices: false
    useAllNodes: false
  waitTimeoutForHealthyOSDInMinutes: 10
